name: "💡 App request"
description: Create a new ticket for a new app request
title: "💡 App request: <title>"
labels: [
  "type: app request"
]
body:
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: dropdown
    id: framework
    attributes:
      label: Select the framework
      multiple: false
      options:
        - Flutter
        - React Native
        - Gradle (kotlin or java)
  - type: textarea
    id: extra_information
    attributes:
      label: "Just give your extra information"
      description: Provide any additional information that might be useful.
      placeholder: "Git source url, documentation, etc."
    validations:
      required: false
