name: Build apps to test the derivations

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC

jobs:
  build-sd-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build SD image
        run: nix build -L '.#smouldering_durtles'
